/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.3.5-310-g04fdfe2e19"
#endif /* AVUTIL_FFVERSION_H */
